In [2]:
# Import dependencies
import requests
import json
import pandas as pd
import numpy as np
import os

In [3]:
# Files to read
historicalNASDAQ = './historical_stock_NASDAQ.csv'
catalogueNASDAQ = './Databases/nasdaq.csv'
# Read files
historicalNASDAQ_df = pd.read_csv(historicalNASDAQ, encoding='utf-8')
catalogueNASDAQ_df = pd.read_csv(catalogueNASDAQ, encoding='utf-8')

In [4]:
catalogueNASDAQ_df

,No,Ticker,Name,Industry,Unnamed: 4
0,1,AAPL,Apple Inc,"Computers, Office Equipment",NaN
1,2,AMZN,Amazon.com Inc,Internet Services and Retailing,NaN
2,3,MSFT,Microsoft Corp,Computer Software,NaN
3,4,FB,Facebook Inc,Internet Services and Retailing,NaN
4,5,GOOGL,Alphabet Inc,Internet Services and Retailing,NaN
...,...,...,...,...,...
95,96,BMRN,BioMarin Pharmaceutical Inc,Drugs & Biotechnology,NaN
96,97,EXPE,Expedia Group Inc,Internet Services and Retailing,NaN
97,98,ULTA,Ulta Beauty Inc,Specialty Retailers,NaN
98,99,WDC,Western Digital Corp,"Computers, Office Equipment",NaN
99,100,LBTYK,Liberty Global PLC,Insurance,NaN

In [7]:
catalogueNASDAQ_df = catalogueNASDAQ_df[['Ticker','Name','Industry']]
catalogueNASDAQ_df= catalogueNASDAQ_df.rename(columns={'Ticker': 'Symbol'})
catalogueNASDAQ_df

   Symbol                         Name                         Industry
0    AAPL                    Apple Inc      Computers, Office Equipment
1    AMZN               Amazon.com Inc  Internet Services and Retailing
2    MSFT               Microsoft Corp                Computer Software
3      FB                 Facebook Inc  Internet Services and Retailing
4   GOOGL                 Alphabet Inc  Internet Services and Retailing
..    ...                          ...                              ...
95   BMRN  BioMarin Pharmaceutical Inc            Drugs & Biotechnology
96   EXPE            Expedia Group Inc  Internet Services and Retailing
97   ULTA              Ulta Beauty Inc              Specialty Retailers
98    WDC         Western Digital Corp      Computers, Office Equipment
99  LBTYK           Liberty Global PLC                        Insurance

[100 rows x 3 columns]

In [10]:
# del historicalNASDAQ_df["currency"]
historicalNASDAQ_df = historicalNASDAQ_df.rename({'symbol': 'Symbol', 'date': 'Date', 
                    'uClose': 'UnadjustedClosePrice','uOpen': 'UnadjustedOpenPrice',
                    'uHigh': 'UnadjustedHighPrice','uLow': 'UnadjustedLowPrice',
                    'uVolume': 'UnadjustedVolume','close': 'AdjustedClosePrice',
                    'open': 'AdjustedOpenPrice','high': 'AdjustedHighPrice',
                    'low': 'AdjustedLowPrice','volume': 'AdjustedVolume',
                    'change': 'ChangefromPreviousDay','changePercent': 'ChangePercentagefromPreviousDay',
                    'label': 'Date2','changeOverTime': 'ChangePercentagefromFirstValue'}, axis=1)
# historicalNASDAQ_df = catalogueNASDAQ_df[['Symbol','Date','Date2','UnadjustedClosePrice','UnadjustedOpenPrice',
#                     'UnadjustedHighPrice','UnadjustedLowPrice','UnadjustedVolume','AdjustedClosePrice',
#                     'AdjustedOpenPrice','AdjustedHighPrice','AdjustedLowPrice','AdjustedVolume',
#                     'ChangefromPreviousDay','ChangePercentagefromPreviousDay','ChangePercentagefromFirstValue']]
historicalNASDAQ_df

,Symbol,Date,UnadjustedClosePrice,UnadjustedOpenPrice,UnadjustedHighPrice,UnadjustedLowPrice,UnadjustedVolume,AdjustedClosePrice,AdjustedOpenPrice,AdjustedHighPrice,AdjustedLowPrice,AdjustedVolume,ChangefromPreviousDay,ChangePercentagefromPreviousDay,Date2,ChangePercentagefromFirstValue
0,AAPL,08/31/2015,115.94,115.83,116.50,114.00,58635323,115.15,116.80,119.41,116.00,56938713,0.000,0.0000,31-Aug-15,0.000000
1,AAPL,09/01/2015,109.60,110.67,116.52,108.21,78386950,112.79,113.35,116.22,112.09,80534174,-5.200,-4.6765,01-Sep-15,-0.045822
2,AAPL,09/02/2015,112.98,115.09,114.26,110.68,61899409,115.88,113.36,115.59,113.76,61959735,4.780,4.3872,02-Sep-15,-0.003898
3,AAPL,09/03/2015,114.67,117.99,114.75,111.05,55434852,110.59,113.87,116.25,113.68,55207240,-1.990,-1.7587,03-Sep-15,-0.021899
4,AAPL,09/04/2015,111.64,111.00,112.70,110.29,52493830,112.93,109.59,114.78,110.89,50851532,-1.100,-1.0015,04-Sep-15,-0.031319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122756,LBTYK,08/24/2020,22.06,22.41,22.37,21.50,3156655,22.54,22.14,22.71,21.55,3156724,0.260,1.1843,24-Aug-20,-0.445840
122757,LBTYK,08/25/2020,22.89,22.31,22.28,22.49,2921851,22.94,21.78,23.07,22.39,2949494,0.508,2.4449,25-Aug-20,-0.450434
122758,LBTYK,08/26/2020,23.41,22.87,23.88,23.00,3256199,23.67,22.15,23.78,22.00,3140750,0.600,2.6455,26-Aug-20,-0.430369
122759,LBTYK,08/27/2020,22.88,23.58,23.00,23.30,2338152,23.72,23.91,23.90,22.80,2308808,0.088,0.3790,27-Aug-20,-0.415945
122760,LBTYK,08/28/2020,23.29,23.59,23.30,22.75,1901997,23.59,23.71,23.18,23.16,1890635,0.230,0.9671,28-Aug-20,-0.423613

In [11]:
historicalNASDAQMerge_df = pd.merge(historicalNASDAQ_df,catalogueNASDAQ_df,on='Symbol',how='outer')
historicalNASDAQMerge_df

,Symbol,Date,UnadjustedClosePrice,UnadjustedOpenPrice,UnadjustedHighPrice,UnadjustedLowPrice,UnadjustedVolume,AdjustedClosePrice,AdjustedOpenPrice,AdjustedHighPrice,AdjustedLowPrice,AdjustedVolume,ChangefromPreviousDay,ChangePercentagefromPreviousDay,Date2,ChangePercentagefromFirstValue,Name,Industry
0,AAPL,08/31/2015,115.94,115.83,116.50,114.00,58635323,115.15,116.80,119.41,116.00,56938713,0.000,0.0000,31-Aug-15,0.000000,Apple Inc,"Computers, Office Equipment"
1,AAPL,09/01/2015,109.60,110.67,116.52,108.21,78386950,112.79,113.35,116.22,112.09,80534174,-5.200,-4.6765,01-Sep-15,-0.045822,Apple Inc,"Computers, Office Equipment"
2,AAPL,09/02/2015,112.98,115.09,114.26,110.68,61899409,115.88,113.36,115.59,113.76,61959735,4.780,4.3872,02-Sep-15,-0.003898,Apple Inc,"Computers, Office Equipment"
3,AAPL,09/03/2015,114.67,117.99,114.75,111.05,55434852,110.59,113.87,116.25,113.68,55207240,-1.990,-1.7587,03-Sep-15,-0.021899,Apple Inc,"Computers, Office Equipment"
4,AAPL,09/04/2015,111.64,111.00,112.70,110.29,52493830,112.93,109.59,114.78,110.89,50851532,-1.100,-1.0015,04-Sep-15,-0.031319,Apple Inc,"Computers, Office Equipment"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122756,LBTYK,08/24/2020,22.06,22.41,22.37,21.50,3156655,22.54,22.14,22.71,21.55,3156724,0.260,1.1843,24-Aug-20,-0.445840,Liberty Global PLC,Insurance
122757,LBTYK,08/25/2020,22.89,22.31,22.28,22.49,2921851,22.94,21.78,23.07,22.39,2949494,0.508,2.4449,25-Aug-20,-0.450434,Liberty Global PLC,Insurance
122758,LBTYK,08/26/2020,23.41,22.87,23.88,23.00,3256199,23.67,22.15,23.78,22.00,3140750,0.600,2.6455,26-Aug-20,-0.430369,Liberty Global PLC,Insurance
122759,LBTYK,08/27/2020,22.88,23.58,23.00,23.30,2338152,23.72,23.91,23.90,22.80,2308808,0.088,0.3790,27-Aug-20,-0.415945,Liberty Global PLC,Insurance
122760,LBTYK,08/28/2020,23.29,23.59,23.30,22.75,1901997,23.59,23.71,23.18,23.16,1890635,0.230,0.9671,28-Aug-20,-0.423613,Liberty Global PLC,Insurance

In [13]:
# Create csv and json file for database
historicalNASDAQMerge_df.to_csv('Databases/historicalStockPriceNASDAQ.csv')
historicalNASDAQMerge_df.to_json('Databases/historicalStockPriceNASDAQ.json',orient = 'records')